version: "2"
services:
  auth-ui:
    image: openlmis/dev-ui:6
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - ui-components
      - ui-layout
    depends_on:
      - ui-components
      - ui-layout
  ui-components:
    image: openlmis/ui-components:5.2.0-RC1
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.0.3-RC1
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmis/auth-ui
